name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./dist/"
          protocol: ftp
          port: 21
          dangerous-clean-slate: false
